const PREFIX = 'PHONES_LIST';

export const FETCH_ATTEMPTED = `${PREFIX}:FETCH:ATTEMPTED`;
export const FETCH_SUCCEEDED = `${PREFIX}:FETCH:SUCCEEDED`;
export const FETCH_FAILED = `${PREFIX}:FETCH:FAILED`;